name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow on tags prefixed with 'v', e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Go
        uses: actions/setup-go@v4  # Remains v4 as it's the latest, but make sure it's compatible with Node 20+
        with:
          go-version: 1.23  # Specify your desired Go version

      - name: Set execute permissions for scripts
        run: |
          chmod +x build.sh
          chmod +x package.sh

      - name: Build binaries
        run: ./build.sh

      - name: Package binaries
        run: ./package.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3  # Remains v3, latest available but ensure Node 20+ compatibility
        with:
          name: packaged-binaries
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: packaged-binaries
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
